### ISSUE TITLE
Updating a membership witness

### ISSUE THREAD

**Issue by pgrinaway** [cambrian/accumulator#42]
I have a simple (and perhaps very naive) question about the membership witness update. Is there a way around requiring the caller to provide the `tracked_elements`? We are trying to use the accumulator to avoid everyone having to maintain the full list of tracked elements. 

Thanks for your help, and apologies if this is a very naive question.

edit: looking at the code, it seems that carrying around the [prime hash product](https://github.com/cambrian/accumulator/blob/master/src/accumulator.rs#L236) of the tracked elements would eliminate the need to provide them in full. Is this a correct understanding?

**Comment by plra** [comment]
Great question, no apologies needed! Our `tracked_elems` is in fact a local object, namely the list of elements added to the accumulator and "managed" by a certain client. (In our [accumulator-demo](https://github.com/cambrian/accumulator-demo), you will see that it is the `utxo_set` maintained by a particular `Bridge<G>` to track all its `User`s' UTXOs.) This is in general much smaller than the global accumulator set, which I assume you mean by "full list of tracked elements." Hence the client's `tracked_elems` scales with its own additions, not all.

Regarding your edit, you are correct. If we did this we could rewrite the loop on line 239 to check for coprimality rather than list membership. However if the size of `tracked_elems` is `n`, `prime_hash_product(tracked_elems)` takes up `O(n)` space as well, so we went with the list for the sake of simplicity.

**Comment by pgrinaway** [comment]
Ok, thanks so much for your answer! To confirm that I am correct about this, I tried the following very simple code. This implies that `tracked_elements` is just the set of elements for which you'd like to update the witness then, and the `untracked_*` parameters will only contain UTXOs from the recent block as they have been added after the witness was updated. Is that correct?

```rust
fn simple_example()
{
    //create an accumulator
    let acc = Accumulator::<Rsa2048, String>::empty();

    // add some initial elements and check that we can verify their membership
    let (acc, proof_utxo_1) = acc.add_with_proof(&["utxo_1".to_string()]);
    assert!(acc.verify_membership_batch(&["utxo_1".to_string()], &proof_utxo_1));

    let (acc, proof_utxo_3) = acc.add_with_proof(&["utxo_2".to_string()]);
    println!("Try to add another element");
    let (acc, proof_utxo_3) = acc.add_with_proof(&["utxo_3".to_string()]);

    println!("Try to add one more");
    let (acc, proof_utxo_4) = acc.add_with_proof(&["utxo_4".to_string()]);

    // now try to update the utxo_3 witness, assuming that UTXO 1 was managed by the same bridge, but not UTXO 2:
    let updated_witness = acc.update_membership_witness(proof_utxo_3.witness.clone(), &["utxo_3".to_string()], &["utxo_4".to_string()], &[]).unwrap();

    let updated_proof = acc.prove_membership(&[("utxo_3".to_string(), updated_witness)]).unwrap();
    assert!(acc.verify_membership(&"utxo_3".to_string(), &updated_proof));
    
}
```

**Comment by whaatt** [comment]
Just wanted to clarify some general concepts before going into your code. Apologies if all this was already clear!

### Preliminaries

A _witness_ is just an accumulator, nothing more or less. So let's consider some witness `w`, which is just an accumulator for a set of elements `U`.

For this witness to be useful, we have to describe it _relative to_ another accumulator `a` (whose set we'll call capital `A`).

Note that there is a discrepancy between `U` and `A`, namely some set of elements `T` equal to the set difference `A - U`. If we described this witness relative to a different accumulator `a'`, this set difference would be a different result `T'`.

### Relative Witnesses

Now we have a natural way of describing witness `w` as a tuple `(a, T)`, consisting of an accumulator and a set of elements. We say that `w` _tracks_ the elements `T` _with respect to_ `a`.

I could give you `w` and `a` to prove to you that `T` is in the accumulator set of `a`, and you would verify this claim by checking `w.add(T) == a` (a simplification, but this is the gist of it). These proofs are what witnesses are useful for.

For a witness `w` in our code, we say that `U` are the `untracked_elems` and `T` are the `tracked_elems` with respect to some accumulator.

### Witness Updates

Let's move to a real-world setting, where I have a global accumulator `a` (whose set is `A`) and some witness `w` tracking elements `T` w.r.t. `a`. (As before, the untracked elements are some set `U`.)

I might have `w` because I'm a user with a UTXO `x`, and when I spend the `x`, I need to prove that it's in the set of `a`. Here, `T = {x}`.

Or I might have `w` because I'm a _bridge node_ (in our parlance), and I'm responsible for keeping UTXOs `x_1, x_2, ..., x_n` valid for several users. Here, `T = {x_1, x_2, ..., x_n}`.

Either way, I'm listening for additions and deletions to `a` in the network (e.g. new blocks being published by blockchain miners). If these changes occur, my witness `w = (a, T)` is no longer valid with respect to the new accumulator `a'`, and a _witness update_ may be required.

When a set of changes (additions or deletions to `a`) come in, we can categorize them as follows:

1. **Tracked additions**: New accumulator elements that this user/bridge wants its witness to track (e.g. someone creates and sends me a UTXO).

2. **Tracked deletions**: Deleted accumulator elements that this user or bridge's witness _has been tracking_ (e.g. I spend a UTXO).

3. **Untracked additions**: New accumulator elements that this user/bridge doesn't care about (e.g. someone creates a UTXO and sends it to a user that isn't me).

4. **Untracked deletions**: Deleted accumulator elements that this user/bridge doesn't care about (e.g. someone that isn't me spends a UTXO).

In cases **(1)** and **(2)**, we actually don't need to update the witness `w`.

_Proof:_ Recall that the current accumulator set of `w` is `U = A - T`. After some tracked additions and deletions, we have `A' - T' = (A + T_add - T_delete) - (T + T_add - T_delete) = A - T = U` as desired.

Cases **(3)** and **(4)** require an update, since `A` changes while `T` remains constant. The accumulator paper has more details on the witness update, but essentially it requires the new accumulator `a' = acc`, the current `T = tracked_elems`, the `untracked_additions`, and the `untracked_deletions`.

### Redux
I wasn't 100% sure what this comment meant:
```Rust
// now try to update the utxo_3 witness, assuming that UTXO 1 was managed by the same bridge, but not UTXO 2:
let updated_witness = acc.update_membership_witness(proof_utxo_3.witness.clone(), &["utxo_3".to_string()], &["utxo_4".to_string()], &[]).unwrap();
```

Nevertheless, I think your general intuition is correct. In your code you create a witness for `"utxo_3"` with respect to an accumulator containing `["utxo_1", "utxo_2", "utxo_3"]`; when the accumulator adds the untracked element `"utxo_4"`, you update your witness accordingly.

Hope this helps! (And please clarify the comment if you get a chance/let me know if things still don't make sense.)

**Comment by pgrinaway** [comment]
Wow, thanks so much for the detailed reply! That is really helpful and clear! And apologies for unclear terminology. 

Basically my comment (which I see was pretty unclear now) was saying that I am in situation (3) above, but I think I had a typo that made it confusing.

I really appreciate the answers + detailed explanation, as well as the library. Thanks a lot!

**Comment by pgrinaway** [comment]
One more question: I was playing around with nonmembership witnesses, and it seems the method to do that requires the entire (global) set of accumulator elements. However, it seems that in [this paper](https://eprint.iacr.org/2018/1188.pdf) it is possible to update a nonmembership witness without having the entire set of accumulated elements on hand. Did I misread that, or is that a feature that could be implemented here?

Thanks again for all your help!

**Comment by whaatt** [comment]
Yep, we don't have this feature and would certainly welcome contributions! Our original target use case (the Bitcoin demo) doesn't make use of non-membership proofs at all, so we have less infrastructure around that at the moment.

Additionally, the `NonMemWitUpdate` procedure in the Boneh/Bünz/Fisch (BBF) paper you've linked does not directly expose the non-membership witness. Doing so would require transferring data linear in the number of elements being proven (page 16).

NB. I couldn't find where in BBF they describe non-membership witness updates, but I know it's certainly possible from [Li/Li/Xue](https://www.cs.purdue.edu/homes/ninghui/papers/accumulator_acns07.pdf) (2007) [Section 4.2].

**Comment by pgrinaway** [comment]
Thanks! That makes sense. Really appreciated!

> I couldn't find where in BBF they describe non-membership witness updates, but I know it's certainly possible from Li/Li/Xue (2007) [Section 4.2].

Ah, yeah, actually they just cite that paper (LLX) in BBF (sec 4.2 `CreateAllMemWit`), where it is actually described. Too many tabs open 🤦‍♂️

**Comment by whaatt** [comment]
(Copied the short primer on witnesses to the repo Wiki.)
